package happypets.ui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class HistorialClinicoFrame extends JFrame {
    private static final long serialVersionUID = 1L;
    private JTextField buscarMascota;
    private JTable tablaConsultas;

    public HistorialClinicoFrame() {
        setTitle("Happy Pets - Historial Clínico");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setBounds(100, 100, 1440, 850);
        setResizable(false);
        JPanel contentPane = new JPanel();
        contentPane.setBackground(new Color(240, 240, 240));
        setContentPane(contentPane);
        contentPane.setLayout(null);
        JPanel topBar = new JPanel();
        topBar.setBounds(0, 0, 1424, 60);
        topBar.setLayout(null);
        topBar.setBackground(new Color(0, 188, 212));
        contentPane.add(topBar);
        JLabel systemTitle = new JLabel("Sistema de Gestión Veterinaria");
        systemTitle.setBounds(28, 17, 500, 28);
        systemTitle.setFont(new Font("SansSerif", Font.BOLD, 18));
        systemTitle.setForeground(Color.WHITE);
        topBar.add(systemTitle);
        JLabel companyTop = new JLabel("Happy Pets");
        companyTop.setBounds(1130, 19, 120, 24);
        companyTop.setFont(new Font("SansSerif", Font.BOLD, 12));
        companyTop.setForeground(Color.WHITE);
        topBar.add(companyTop);
        JLabel userTop = new JLabel("Usuario:");
        userTop.setBounds(1250, 19, 150, 24);
        userTop.setFont(new Font("SansSerif", Font.PLAIN, 12));
        userTop.setForeground(Color.WHITE);
        topBar.add(userTop);
        JPanel moduleBar = new JPanel();
        moduleBar.setBounds(22, 78, 1380, 78);
        moduleBar.setLayout(null);
        moduleBar.setBackground(new Color(0, 188, 212));
        contentPane.add(moduleBar);
        JLabel logo = new JLabel("HP");
        logo.setBounds(20, 18, 50, 42);
        logo.setFont(new Font("SansSerif", Font.BOLD, 20));
        logo.setForeground(Color.WHITE);
        moduleBar.add(logo);
        JLabel moduleTitle = new JLabel("Historial Clínico de Mascotas");
        moduleTitle.setBounds(80, 15, 800, 30);
        moduleTitle.setFont(new Font("SansSerif", Font.BOLD, 21));
        moduleTitle.setForeground(Color.WHITE);
        moduleBar.add(moduleTitle);
        JLabel moduleSubtitle = new JLabel("Consulta de visitas y evolución por mascota");
        moduleSubtitle.setBounds(80, 46, 900, 20);
        moduleSubtitle.setFont(new Font("SansSerif", Font.PLAIN, 11));
        moduleSubtitle.setForeground(Color.WHITE);
        moduleBar.add(moduleSubtitle);
        JLabel companyModule = new JLabel("Happy Pets");
        companyModule.setBounds(1180, 28, 170, 26);
        companyModule.setFont(new Font("SansSerif", Font.BOLD, 12));
        companyModule.setForeground(Color.WHITE);
        companyModule.setHorizontalAlignment(SwingConstants.RIGHT);
        moduleBar.add(companyModule);
        JPanel filters = new JPanel();
        filters.setBounds(22, 172, 1380, 54);
        filters.setLayout(null);
        filters.setBackground(Color.WHITE);
        filters.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(filters);
        JLabel searchPetLabel = new JLabel("Buscar mascota:");
        searchPetLabel.setBounds(16, 16, 130, 20);
        searchPetLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        filters.add(searchPetLabel);
        buscarMascota = new JTextField();
        buscarMascota.setBounds(146, 11, 270, 30);
        filters.add(buscarMascota);
        JButton searchPet = new JButton("Buscar");
        searchPet.setBounds(426, 10, 86, 32);
        filters.add(searchPet);
        searchPet.addActionListener(e -> Ui.pendiente(this, "Buscar mascota"));
        JLabel periodLabel = new JLabel("Período:");
        periodLabel.setBounds(550, 16, 80, 20);
        periodLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        filters.add(periodLabel);
        JComboBox<String> periodo = new JComboBox<>(new String[] {"Todas las fechas", "Último año", "Últimos 3 años"});
        periodo.setBounds(630, 11, 160, 30);
        filters.add(periodo);
        JPanel patientSummary = new JPanel();
        patientSummary.setBounds(22, 242, 1380, 54);
        patientSummary.setLayout(null);
        patientSummary.setBackground(Color.WHITE);
        patientSummary.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(patientSummary);
        JLabel summary0 = new JLabel("Mascota seleccionada");
        summary0.setBounds(14, 16, 260, 22);
        summary0.setFont(new Font("SansSerif", Font.BOLD, 11));
        patientSummary.add(summary0);
        JLabel summary1 = new JLabel("Cliente responsable");
        summary1.setBounds(284, 16, 260, 22);
        summary1.setFont(new Font("SansSerif", Font.BOLD, 11));
        patientSummary.add(summary1);
        JLabel summary2 = new JLabel("Especie y raza");
        summary2.setBounds(554, 16, 260, 22);
        summary2.setFont(new Font("SansSerif", Font.BOLD, 11));
        patientSummary.add(summary2);
        JLabel summary3 = new JLabel("Última consulta");
        summary3.setBounds(824, 16, 260, 22);
        summary3.setFont(new Font("SansSerif", Font.BOLD, 11));
        patientSummary.add(summary3);
        JLabel summary4 = new JLabel("Consultas registradas");
        summary4.setBounds(1094, 16, 260, 22);
        summary4.setFont(new Font("SansSerif", Font.BOLD, 11));
        patientSummary.add(summary4);
        JPanel historyCard = new JPanel();
        historyCard.setBounds(22, 312, 1380, 418);
        historyCard.setLayout(null);
        historyCard.setBackground(Color.WHITE);
        historyCard.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(historyCard);
        JPanel historyTitle = new JPanel();
        historyTitle.setBounds(16, 16, 1348, 40);
        historyTitle.setLayout(null);
        historyTitle.setBackground(new Color(0, 188, 212));
        historyCard.add(historyTitle);
        JLabel historyTitleLabel = new JLabel("Consultas de la mascota");
        historyTitleLabel.setBounds(14, 9, 500, 22);
        historyTitleLabel.setFont(new Font("SansSerif", Font.BOLD, 12));
        historyTitleLabel.setForeground(Color.WHITE);
        historyTitle.add(historyTitleLabel);
        tablaConsultas = new JTable(new DefaultTableModel(new Object[][] {}, new String[] {"N.º", "Fecha", "Motivo", "Diagnóstico", "Tratamiento", "Veterinario", "Estado", "Acción"}));
        tablaConsultas.setRowHeight(30);
        JScrollPane tablaConsultasScroll = new JScrollPane(tablaConsultas);
        tablaConsultasScroll.setBounds(16, 70, 1348, 330);
        historyCard.add(tablaConsultasScroll);
        JPanel footer = new JPanel();
        footer.setBounds(22, 748, 1380, 54);
        footer.setLayout(null);
        footer.setBackground(Color.WHITE);
        footer.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(footer);
        JLabel moduleFooter = new JLabel("Módulo: Historial Clínico");
        moduleFooter.setBounds(14, 16, 420, 22);
        moduleFooter.setFont(new Font("SansSerif", Font.PLAIN, 11));
        footer.add(moduleFooter);
        JButton exportHistory = new JButton("Exportar PDF");
        exportHistory.setBounds(1248, 10, 112, 32);
        footer.add(exportHistory);
        exportHistory.addActionListener(e -> Ui.pendiente(this, "Exportar PDF"));
        JButton printHistory = new JButton("Imprimir historial");
        printHistory.setBounds(1090, 10, 150, 32);
        footer.add(printHistory);
        printHistory.addActionListener(e -> Ui.pendiente(this, "Imprimir historial"));
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new HistorialClinicoFrame().setVisible(true));
    }
}
