package happypets.ui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class ClientesMascotasFrame extends JFrame {
    private static final long serialVersionUID = 1L;
    private JTextField busqueda;
    private JTextField nombres;
    private JTextField documento;
    private JTextField telefono;
    private JTextField telefonoSecundario;
    private JTextField correo;
    private JTextField direccion;
    private JTextField ciudad;
    private JTextArea notas;
    private JTable tablaMascotas;

    public ClientesMascotasFrame() {
        setTitle("Happy Pets - Clientes y Mascotas");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setBounds(100, 100, 1440, 850);
        setResizable(false);
        JPanel contentPane = new JPanel();
        contentPane.setBackground(new Color(240, 240, 240));
        setContentPane(contentPane);
        contentPane.setLayout(null);
        JPanel topBar = new JPanel();
        topBar.setBounds(0, 0, 1424, 60);
        topBar.setLayout(null);
        topBar.setBackground(new Color(0, 188, 212));
        contentPane.add(topBar);
        JLabel systemTitle = new JLabel("Sistema de Gestión Veterinaria");
        systemTitle.setBounds(28, 17, 500, 28);
        systemTitle.setFont(new Font("SansSerif", Font.BOLD, 18));
        systemTitle.setForeground(Color.WHITE);
        topBar.add(systemTitle);
        JLabel companyTop = new JLabel("Happy Pets");
        companyTop.setBounds(1130, 19, 120, 24);
        companyTop.setFont(new Font("SansSerif", Font.BOLD, 12));
        companyTop.setForeground(Color.WHITE);
        topBar.add(companyTop);
        JLabel userTop = new JLabel("Usuario:");
        userTop.setBounds(1250, 19, 150, 24);
        userTop.setFont(new Font("SansSerif", Font.PLAIN, 12));
        userTop.setForeground(Color.WHITE);
        topBar.add(userTop);
        JPanel moduleBar = new JPanel();
        moduleBar.setBounds(22, 78, 1380, 78);
        moduleBar.setLayout(null);
        moduleBar.setBackground(new Color(0, 188, 212));
        contentPane.add(moduleBar);
        JLabel logo = new JLabel("HP");
        logo.setBounds(20, 18, 50, 42);
        logo.setFont(new Font("SansSerif", Font.BOLD, 20));
        logo.setForeground(Color.WHITE);
        moduleBar.add(logo);
        JLabel moduleTitle = new JLabel("Mantenimiento de Clientes");
        moduleTitle.setBounds(80, 15, 800, 30);
        moduleTitle.setFont(new Font("SansSerif", Font.BOLD, 21));
        moduleTitle.setForeground(Color.WHITE);
        moduleBar.add(moduleTitle);
        JLabel moduleSubtitle = new JLabel("Registro de clientes y mascotas vinculadas");
        moduleSubtitle.setBounds(80, 46, 900, 20);
        moduleSubtitle.setFont(new Font("SansSerif", Font.PLAIN, 11));
        moduleSubtitle.setForeground(Color.WHITE);
        moduleBar.add(moduleSubtitle);
        JLabel companyModule = new JLabel("Happy Pets");
        companyModule.setBounds(1180, 28, 170, 26);
        companyModule.setFont(new Font("SansSerif", Font.BOLD, 12));
        companyModule.setForeground(Color.WHITE);
        companyModule.setHorizontalAlignment(SwingConstants.RIGHT);
        moduleBar.add(companyModule);
        JPanel actions = new JPanel();
        actions.setBounds(22, 172, 1380, 54);
        actions.setLayout(null);
        actions.setBackground(Color.WHITE);
        actions.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(actions);
        JLabel clientsLabel = new JLabel("Clientes:");
        clientsLabel.setBounds(16, 16, 65, 20);
        clientsLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        actions.add(clientsLabel);
        JButton listClients = new JButton("Listar clientes");
        listClients.setBounds(82, 10, 125, 32);
        actions.add(listClients);
        listClients.addActionListener(e -> Ui.pendiente(this, "Listar clientes"));
        JButton newClient = new JButton("Nuevo cliente");
        newClient.setBounds(217, 10, 116, 32);
        actions.add(newClient);
        newClient.addActionListener(e -> limpiarFormulario());
        JButton modifyClient = new JButton("Modificar cliente");
        modifyClient.setBounds(343, 10, 130, 32);
        actions.add(modifyClient);
        modifyClient.addActionListener(e -> Ui.pendiente(this, "Modificar cliente"));
        JButton deleteClient = new JButton("Eliminar cliente");
        deleteClient.setBounds(483, 10, 120, 32);
        actions.add(deleteClient);
        deleteClient.addActionListener(e -> Ui.pendiente(this, "Eliminar cliente"));
        JLabel searchLabel = new JLabel("Buscar por DNI o apellido:");
        searchLabel.setBounds(630, 16, 190, 20);
        searchLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        actions.add(searchLabel);
        busqueda = new JTextField();
        busqueda.setBounds(824, 11, 240, 30);
        actions.add(busqueda);
        JButton searchClient = new JButton("Buscar");
        searchClient.setBounds(1074, 10, 90, 32);
        actions.add(searchClient);
        searchClient.addActionListener(e -> Ui.pendiente(this, "Buscar cliente"));
        JPanel clientCard = new JPanel();
        clientCard.setBounds(22, 242, 670, 488);
        clientCard.setLayout(null);
        clientCard.setBackground(Color.WHITE);
        clientCard.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(clientCard);
        JPanel clientCardTitle = new JPanel();
        clientCardTitle.setBounds(16, 16, 638, 40);
        clientCardTitle.setLayout(null);
        clientCardTitle.setBackground(new Color(0, 188, 212));
        clientCard.add(clientCardTitle);
        JLabel clientTitle = new JLabel("Ficha de Registro del Cliente");
        clientTitle.setBounds(14, 8, 580, 24);
        clientTitle.setFont(new Font("SansSerif", Font.BOLD, 12));
        clientTitle.setForeground(Color.WHITE);
        clientCardTitle.add(clientTitle);
        JLabel labelnombres = new JLabel("Nombres y apellidos*:");
        labelnombres.setBounds(16, 83, 170, 22);
        labelnombres.setFont(new Font("SansSerif", Font.PLAIN, 12));
        labelnombres.setHorizontalAlignment(SwingConstants.RIGHT);
        clientCard.add(labelnombres);
        nombres = new JTextField();
        nombres.setBounds(192, 78, 455, 30);
        clientCard.add(nombres);
        JLabel labeldocumento = new JLabel("DNI / CE*:");
        labeldocumento.setBounds(16, 121, 170, 22);
        labeldocumento.setFont(new Font("SansSerif", Font.PLAIN, 12));
        labeldocumento.setHorizontalAlignment(SwingConstants.RIGHT);
        clientCard.add(labeldocumento);
        documento = new JTextField();
        documento.setBounds(192, 116, 455, 30);
        clientCard.add(documento);
        JLabel labeltelefono = new JLabel("Teléfono de contacto*:");
        labeltelefono.setBounds(16, 159, 170, 22);
        labeltelefono.setFont(new Font("SansSerif", Font.PLAIN, 12));
        labeltelefono.setHorizontalAlignment(SwingConstants.RIGHT);
        clientCard.add(labeltelefono);
        telefono = new JTextField();
        telefono.setBounds(192, 154, 455, 30);
        clientCard.add(telefono);
        JLabel labeltelefonoSecundario = new JLabel("Teléfono secundario:");
        labeltelefonoSecundario.setBounds(16, 197, 170, 22);
        labeltelefonoSecundario.setFont(new Font("SansSerif", Font.PLAIN, 12));
        labeltelefonoSecundario.setHorizontalAlignment(SwingConstants.RIGHT);
        clientCard.add(labeltelefonoSecundario);
        telefonoSecundario = new JTextField();
        telefonoSecundario.setBounds(192, 192, 455, 30);
        clientCard.add(telefonoSecundario);
        JLabel labelcorreo = new JLabel("Correo electrónico*:");
        labelcorreo.setBounds(16, 235, 170, 22);
        labelcorreo.setFont(new Font("SansSerif", Font.PLAIN, 12));
        labelcorreo.setHorizontalAlignment(SwingConstants.RIGHT);
        clientCard.add(labelcorreo);
        correo = new JTextField();
        correo.setBounds(192, 230, 455, 30);
        clientCard.add(correo);
        JLabel labeldireccion = new JLabel("Dirección:");
        labeldireccion.setBounds(16, 273, 170, 22);
        labeldireccion.setFont(new Font("SansSerif", Font.PLAIN, 12));
        labeldireccion.setHorizontalAlignment(SwingConstants.RIGHT);
        clientCard.add(labeldireccion);
        direccion = new JTextField();
        direccion.setBounds(192, 268, 455, 30);
        clientCard.add(direccion);
        JLabel labelciudad = new JLabel("Distrito / Ciudad:");
        labelciudad.setBounds(16, 311, 170, 22);
        labelciudad.setFont(new Font("SansSerif", Font.PLAIN, 12));
        labelciudad.setHorizontalAlignment(SwingConstants.RIGHT);
        clientCard.add(labelciudad);
        ciudad = new JTextField();
        ciudad.setBounds(192, 306, 455, 30);
        clientCard.add(ciudad);
        JLabel labelNotes = new JLabel("Notas de contacto:");
        labelNotes.setBounds(16, 352, 170, 22);
        labelNotes.setFont(new Font("SansSerif", Font.PLAIN, 12));
        labelNotes.setHorizontalAlignment(SwingConstants.RIGHT);
        clientCard.add(labelNotes);
        notas = new JTextArea();
        JScrollPane notesScroll = new JScrollPane(notas);
        notesScroll.setBounds(192, 350, 455, 52);
        clientCard.add(notesScroll);
        JButton saveClient = new JButton("Guardar cambios");
        saveClient.setBounds(425, 434, 132, 32);
        clientCard.add(saveClient);
        saveClient.addActionListener(e -> Ui.pendiente(this, "Guardar cliente"));
        JButton cancelClient = new JButton("Cancelar");
        cancelClient.setBounds(567, 434, 80, 32);
        clientCard.add(cancelClient);
        cancelClient.addActionListener(e -> limpiarFormulario());
        JPanel petCard = new JPanel();
        petCard.setBounds(710, 242, 692, 488);
        petCard.setLayout(null);
        petCard.setBackground(Color.WHITE);
        petCard.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(petCard);
        JPanel petCardTitle = new JPanel();
        petCardTitle.setBounds(16, 16, 660, 46);
        petCardTitle.setLayout(null);
        petCardTitle.setBackground(new Color(0, 188, 212));
        petCard.add(petCardTitle);
        JLabel petsTitle = new JLabel("Mascotas vinculadas");
        petsTitle.setBounds(12, 11, 230, 24);
        petsTitle.setFont(new Font("SansSerif", Font.BOLD, 12));
        petsTitle.setForeground(Color.WHITE);
        petCardTitle.add(petsTitle);
        JButton newPet = new JButton("Nueva mascota");
        newPet.setBounds(268, 7, 117, 32);
        petCardTitle.add(newPet);
        newPet.addActionListener(e -> Ui.pendiente(this, "Registrar mascota"));
        JButton modifyPet = new JButton("Modificar mascota");
        modifyPet.setBounds(393, 7, 126, 32);
        petCardTitle.add(modifyPet);
        modifyPet.addActionListener(e -> Ui.pendiente(this, "Modificar mascota"));
        JButton deletePet = new JButton("Eliminar mascota");
        deletePet.setBounds(527, 7, 125, 32);
        petCardTitle.add(deletePet);
        deletePet.addActionListener(e -> Ui.pendiente(this, "Eliminar mascota"));
        tablaMascotas = new JTable(new DefaultTableModel(new Object[][] {}, new String[] {"Código", "Nombre", "Especie", "Raza", "Edad", "Sexo", "Estado"}));
        tablaMascotas.setRowHeight(30);
        JScrollPane tablaMascotasScroll = new JScrollPane(tablaMascotas);
        tablaMascotasScroll.setBounds(16, 77, 660, 340);
        petCard.add(tablaMascotasScroll);
        JPanel petSummary = new JPanel();
        petSummary.setBounds(16, 429, 660, 43);
        petSummary.setLayout(null);
        petSummary.setBackground(new Color(247, 247, 247));
        petSummary.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        petCard.add(petSummary);
        JLabel petSummary0 = new JLabel("Mascota seleccionada");
        petSummary0.setBounds(12, 12, 158, 20);
        petSummary0.setFont(new Font("SansSerif", Font.BOLD, 11));
        petSummary.add(petSummary0);
        JLabel petSummary1 = new JLabel("Peso actual");
        petSummary1.setBounds(174, 12, 158, 20);
        petSummary1.setFont(new Font("SansSerif", Font.BOLD, 11));
        petSummary.add(petSummary1);
        JLabel petSummary2 = new JLabel("Plan vacunal");
        petSummary2.setBounds(336, 12, 158, 20);
        petSummary2.setFont(new Font("SansSerif", Font.BOLD, 11));
        petSummary.add(petSummary2);
        JLabel petSummary3 = new JLabel("Alergias");
        petSummary3.setBounds(498, 12, 158, 20);
        petSummary3.setFont(new Font("SansSerif", Font.BOLD, 11));
        petSummary.add(petSummary3);
        JPanel footer = new JPanel();
        footer.setBounds(22, 748, 1380, 54);
        footer.setLayout(null);
        footer.setBackground(Color.WHITE);
        footer.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(footer);
        JLabel moduleFooter = new JLabel("Módulo: Clientes y Mascotas");
        moduleFooter.setBounds(14, 16, 420, 22);
        moduleFooter.setFont(new Font("SansSerif", Font.PLAIN, 11));
        footer.add(moduleFooter);
        JButton finish = new JButton("Guardar y finalizar");
        finish.setBounds(1206, 10, 154, 32);
        footer.add(finish);
        finish.addActionListener(e -> Ui.pendiente(this, "Guardar y finalizar"));
        JButton exportData = new JButton("Exportar datos");
        exportData.setBounds(1076, 10, 122, 32);
        footer.add(exportData);
        exportData.addActionListener(e -> Ui.pendiente(this, "Exportar datos"));
    }


    private void limpiarFormulario() {
        nombres.setText("");
        documento.setText("");
        telefono.setText("");
        telefonoSecundario.setText("");
        correo.setText("");
        direccion.setText("");
        ciudad.setText("");
        notas.setText("");
        busqueda.setText("");
        ((DefaultTableModel) tablaMascotas.getModel()).setRowCount(0);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new ClientesMascotasFrame().setVisible(true));
    }
}
