package happypets.ui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class ConstanciasCertificadosFrame extends JFrame {
    private static final long serialVersionUID = 1L;
    private JTextField busqueda;
    private JTable tablaDocumentos;

    public ConstanciasCertificadosFrame() {
        setTitle("Happy Pets - Constancias y Certificados");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setBounds(100, 100, 1440, 850);
        setResizable(false);
        JPanel contentPane = new JPanel();
        contentPane.setBackground(new Color(240, 240, 240));
        setContentPane(contentPane);
        contentPane.setLayout(null);
        JPanel topBar = new JPanel();
        topBar.setBounds(0, 0, 1424, 60);
        topBar.setLayout(null);
        topBar.setBackground(new Color(0, 188, 212));
        contentPane.add(topBar);
        JLabel systemTitle = new JLabel("Sistema de Gestión Veterinaria");
        systemTitle.setBounds(28, 17, 500, 28);
        systemTitle.setFont(new Font("SansSerif", Font.BOLD, 18));
        systemTitle.setForeground(Color.WHITE);
        topBar.add(systemTitle);
        JLabel companyTop = new JLabel("Happy Pets");
        companyTop.setBounds(1130, 19, 120, 24);
        companyTop.setFont(new Font("SansSerif", Font.BOLD, 12));
        companyTop.setForeground(Color.WHITE);
        topBar.add(companyTop);
        JLabel userTop = new JLabel("Usuario:");
        userTop.setBounds(1250, 19, 150, 24);
        userTop.setFont(new Font("SansSerif", Font.PLAIN, 12));
        userTop.setForeground(Color.WHITE);
        topBar.add(userTop);
        JPanel moduleBar = new JPanel();
        moduleBar.setBounds(22, 78, 1380, 78);
        moduleBar.setLayout(null);
        moduleBar.setBackground(new Color(0, 188, 212));
        contentPane.add(moduleBar);
        JLabel logo = new JLabel("HP");
        logo.setBounds(20, 18, 50, 42);
        logo.setFont(new Font("SansSerif", Font.BOLD, 20));
        logo.setForeground(Color.WHITE);
        moduleBar.add(logo);
        JLabel moduleTitle = new JLabel("Constancias y Certificados");
        moduleTitle.setBounds(80, 15, 800, 30);
        moduleTitle.setFont(new Font("SansSerif", Font.BOLD, 21));
        moduleTitle.setForeground(Color.WHITE);
        moduleBar.add(moduleTitle);
        JLabel moduleSubtitle = new JLabel("Consulta de documentos disponibles por mascota");
        moduleSubtitle.setBounds(80, 46, 900, 20);
        moduleSubtitle.setFont(new Font("SansSerif", Font.PLAIN, 11));
        moduleSubtitle.setForeground(Color.WHITE);
        moduleBar.add(moduleSubtitle);
        JLabel companyModule = new JLabel("Happy Pets");
        companyModule.setBounds(1180, 28, 170, 26);
        companyModule.setFont(new Font("SansSerif", Font.BOLD, 12));
        companyModule.setForeground(Color.WHITE);
        companyModule.setHorizontalAlignment(SwingConstants.RIGHT);
        moduleBar.add(companyModule);
        JPanel filters = new JPanel();
        filters.setBounds(22, 172, 1380, 54);
        filters.setLayout(null);
        filters.setBackground(Color.WHITE);
        filters.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(filters);
        JLabel searchLabel = new JLabel("Buscar cliente o mascota:");
        searchLabel.setBounds(16, 16, 180, 20);
        searchLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        filters.add(searchLabel);
        busqueda = new JTextField();
        busqueda.setBounds(196, 11, 270, 30);
        filters.add(busqueda);
        JButton search = new JButton("Buscar");
        search.setBounds(476, 10, 86, 32);
        filters.add(search);
        search.addActionListener(e -> Ui.pendiente(this, "Buscar cliente o mascota"));
        JLabel typeLabel = new JLabel("Tipo de documento:");
        typeLabel.setBounds(590, 16, 145, 20);
        typeLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        filters.add(typeLabel);
        JComboBox<String> tipo = new JComboBox<>(new String[] {"Todos", "Tarjeta de vacunación", "Historial de recetas médicas", "Historial clínico", "Certificado de vacunación"});
        tipo.setBounds(740, 11, 260, 30);
        filters.add(tipo);
        JPanel patientSummary = new JPanel();
        patientSummary.setBounds(22, 242, 1380, 54);
        patientSummary.setLayout(null);
        patientSummary.setBackground(Color.WHITE);
        patientSummary.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(patientSummary);
        JLabel summary0 = new JLabel("Mascota seleccionada");
        summary0.setBounds(14, 16, 325, 22);
        summary0.setFont(new Font("SansSerif", Font.BOLD, 11));
        patientSummary.add(summary0);
        JLabel summary1 = new JLabel("Cliente responsable");
        summary1.setBounds(349, 16, 325, 22);
        summary1.setFont(new Font("SansSerif", Font.BOLD, 11));
        patientSummary.add(summary1);
        JLabel summary2 = new JLabel("Especie y raza");
        summary2.setBounds(684, 16, 325, 22);
        summary2.setFont(new Font("SansSerif", Font.BOLD, 11));
        patientSummary.add(summary2);
        JLabel summary3 = new JLabel("Documentos mostrados");
        summary3.setBounds(1019, 16, 325, 22);
        summary3.setFont(new Font("SansSerif", Font.BOLD, 11));
        patientSummary.add(summary3);
        JPanel documentsCard = new JPanel();
        documentsCard.setBounds(22, 312, 1380, 418);
        documentsCard.setLayout(null);
        documentsCard.setBackground(Color.WHITE);
        documentsCard.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(documentsCard);
        JPanel documentsTitle = new JPanel();
        documentsTitle.setBounds(16, 16, 1348, 40);
        documentsTitle.setLayout(null);
        documentsTitle.setBackground(new Color(0, 188, 212));
        documentsCard.add(documentsTitle);
        JLabel documentsTitleLabel = new JLabel("Documentos disponibles");
        documentsTitleLabel.setBounds(14, 9, 500, 22);
        documentsTitleLabel.setFont(new Font("SansSerif", Font.BOLD, 12));
        documentsTitleLabel.setForeground(Color.WHITE);
        documentsTitle.add(documentsTitleLabel);
        tablaDocumentos = new JTable(new DefaultTableModel(new Object[][] {}, new String[] {"Documento", "Mascota", "Descripción", "Última actualización", "Disponibilidad", "Ver", "Descargar"}));
        tablaDocumentos.setRowHeight(30);
        JScrollPane tablaDocumentosScroll = new JScrollPane(tablaDocumentos);
        tablaDocumentosScroll.setBounds(16, 70, 1348, 330);
        documentsCard.add(tablaDocumentosScroll);
        JPanel footer = new JPanel();
        footer.setBounds(22, 748, 1380, 54);
        footer.setLayout(null);
        footer.setBackground(Color.WHITE);
        footer.setBorder(BorderFactory.createLineBorder(new Color(120, 120, 120)));
        contentPane.add(footer);
        JLabel moduleFooter = new JLabel("Módulo: Constancias y Certificados");
        moduleFooter.setBounds(14, 16, 420, 22);
        moduleFooter.setFont(new Font("SansSerif", Font.PLAIN, 11));
        footer.add(moduleFooter);
        JButton printDocuments = new JButton("Imprimir listado");
        printDocuments.setBounds(1210, 10, 150, 32);
        footer.add(printDocuments);
        printDocuments.addActionListener(e -> Ui.pendiente(this, "Imprimir listado"));
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new ConstanciasCertificadosFrame().setVisible(true));
    }
}
